name: zip_way
description: Flutter project for traveling.

# Publishing
publish_to: 'none'  # Prevent accidental publishing

# Versioning
version: 1.0.0+1

# Environment
environment:
  sdk: '>=3.2.0 <4.0.0'

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core packages
  intl: 0.19.0

  # UI packages
  feather_icons: ^1.2.0
  flutter_portal: ^1.1.4
  flutter_svg: ^2.0.7
  camera: ^0.9.4+5
  http: ^1.2.1
  flutter_map: ^7.0.2

  # Firebase packages
  # firebase_core: ^2.14.0
  # firebase_auth: ^4.6.3

  # State management and data handling
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dartz: ^0.10.1

  # Dependency injection
  get_it: ^7.6.0

  # Serialization
  json_annotation: ^4.8.1
  json_serializable: any

  # Logging
  simple_logger: ^1.9.0+2

  # Database
  cloud_firestore: ^4.8.4

  # Reactive programming
  rxdart: ^0.27.7

  # Other utilities
  currency_picker: ^2.0.19
  gap: ^3.0.1
  freezed: ^2.4.5
  rx_widgets: ^4.2.1
  uuid: ^4.2.1
  url_launcher: ^6.2.1
  badges: ^3.1.2
  flutter_rating_bar: ^4.0.1
  freezed_annotation: ^2.4.1
  collection: ^1.17.2
  flutter_translate: ^4.1.0
  google_maps_flutter: ^2.9.0

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # Linting and code analysis
  flutter_lints: ^4.0.0
  class_match_file_name: ^0.1.4
  lints: ^4.0.0
  build_runner: ^2.4.6

# Flutter configuration
flutter:
  generate: true
  uses-material-design: true

  # Assets
  assets:
    - assets/
    - assets/logo/
    - assets/i18n/
