name: zip_way
description: Flutter project for volunteering.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dartz: ^0.10.1
  dio: ^5.0.0
  equatable: ^2.0.7
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_bloc: ^9.0.0
  flutter_gen: ^5.8.0
  flutter_local_notifications: ^19.0.0
  flutter_map: ^7.0.2
  flutter_native_splash: ^2.4.4
  flutter_translate: ^4.1.0
  freezed: ^2.4.5
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  geolocator: ^13.0.1
  google_fonts: ^6.2.1
  get_it: ^8.0.3
  image_picker: ^1.1.2
  intl: 0.19.0
  json_annotation: ^4.9.0
  json_serializable: any
  latlong2: ^0.9.1
  mime: ^2.0.0
  provider: ^6.1.2
  rxdart: ^0.27.7
  rx_widgets: ^4.2.1
  simple_logger: ^1.10.0
  uuid: ^4.2.1
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.15
  class_match_file_name: ^0.2.2
  flutter_gen_runner: any
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/i18n/
    - assets/logo/
