// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCihLWKE8FyAxwKdQ01wNc_949xnlWZVzA',
    appId: '1:1205836066:android:2f1dbc43e6c4c1dbd5ad7b',
    messagingSenderId: '1205836066',
    projectId: 'zip-way',
    databaseURL: 'https://zip-way-default-rtdb.firebaseio.com',
    storageBucket: 'zip-way.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7SOPY1FphTCleXb8dOlj2_0WN8PUAkCI',
    appId: '1:1205836066:ios:d41b4ea298aa8a92d5ad7b',
    messagingSenderId: '1205836066',
    projectId: 'zip-way',
    databaseURL: 'https://zip-way-default-rtdb.firebaseio.com',
    storageBucket: 'zip-way.firebasestorage.app',
    iosClientId: '1205836066-cesjb9mo8ep0tj4jbn8afc0julmc26rp.apps.googleusercontent.com',
    iosBundleId: 'com.example.zipWay',
  );
}
